services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Ayto\ResetPasswordBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Entity/'
            - '../../ApiResource/'
            - '../../Tests/'
            - '../../Resources/'

    reset_password.email_sender:
        class: Ayto\ResetPasswordBundle\Service\ResetPasswordEmailSender
        arguments:
            $mailer: '@mailer'
            $twig: '@twig'
            $urlGenerator: '@router'
            # $fromEmail and $tokenLifetime will be set by the extension

    Ayto\ResetPasswordBundle\Service\ResetPasswordService:
        arguments:
            $frontendResetUrl: '%reset_password.frontend_reset_url%'
            $userClass: '%reset_password.user_class%'
