api_platform:
    formats:
        json: ['application/json']
        jsonld: ['application/ld+json']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
    path_segment_name_generator: api_platform.path_segment_name_generator.dash
