reset_password.api:
    resource: '@ResetPasswordBundle/src/ApiResource/'
    type: api_platform
    prefix: /api

reset_password.web:
    resource: '@ResetPasswordBundle/src/Controller/'
    type: attribute
